apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-window
  labels:
    app: chat-window
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-window
  template:
    metadata:
      labels:
        app: chat-window
    spec:
      containers:
      - name: chat-window
        image: default-route-openshift-image-registry.apps.xr42gryb.eastus.aroapp.io/pipelines/chat-window:latest
        ports:
        - containerPort: 8080
