apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: eso-secret-store
    kind: ClusterSecretStore
  target:
    name: registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .dockerregistryurl | toString }}": {
                "username": "{{ .username | toString }}",
                "password": "{{ .password | toString }}",
                "email": "{{ .email | toString }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: secret/docker-username
  - secretKey: password
    remoteRef:
      key: secret/docker-password
  - secretKey: email
    remoteRef:
      key: secret/docker-email
  - secretKey: dockerregistryurl
    remoteRef:
      key: secret/docker-registry-url
