apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources to be imported from the base configuration
bases:
- ../base

# Common labels for this overlay
commonLabels:
  env: dev

images:
- name: default-route-openshift-image-registry.apps.xr42gryb.eastus.aroapp.io/pipelines/chat-window
  newTag: "latest"
