---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-window
  namespace: openshift-gitops
  labels:
    repo: app_manifests
    runtime: "default"
    path: frontends_chatwindow
    type: ui
spec:
  destination:
    namespace: chat-window
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/ml-app-of-apps'
    path: 'openshift/chat'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
