---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: nvidia-gpu-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/ml-app-of-apps'
    path: 'openshift/operator/gpu-operator'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: false
