---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mixtral7b
  namespace: openshift-gitops
spec:
  destination:
    namespace: collective
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/ml-app-of-apps'
    path: 'openshift/mixtral'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
