apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-config
  namespace: quay-registry
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: app/secrets
        metadataPolicy: None
        property: AWS_ACCESS_KEY
      secretKey: accessKey
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: infra/secrets
        metadataPolicy: None
        property: s3_bucket
      secretKey: bucket
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: app/secrets
        metadataPolicy: None
        property: AWS_SECRET_ACCESS_KEY
      secretKey: secretKey
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-secret-store
    namespace: openshift-gitops
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - configMap:
            items:
              - key: config.yaml
                templateAs: Values
            name: quay-config-template
          target: Data
